#!/bin/sh

MACH_CMD=./platform/mach

# Check to see if ./platform/mach exists.

if [ ! -f "$MACH_CMD" ]; then
  printf "Error: There is no platform codebase.\n"
  printf "Make sure you have checked out the platform submodule before using this command.\n"
  exit 1
fi

# Pass all arguments to ./platform/mach.
$MACH_CMD $@